export const stateCodes = [
  { sc: 'AN', sn: 'Andaman and Nicobar Islands' },
  { sc: 'AP', sn: 'Andhra Pradesh' },
  { sc: 'AR', sn: 'Arunachal Pradesh' },
  { sc: 'AS', sn: 'Assam' },
  { sc: 'BR', sn: 'Bihar' },
  { sc: 'CH', sn: 'Chandigarh' },
  { sc: 'CT', sn: 'Chhattisgarh' },
  { sc: 'DL', sn: 'Delhi' },
  { sc: 'DN', sn: 'Dadra and Nagar Haveli and Daman and Diu' },
  { sc: 'GA', sn: 'Goa' },
  { sc: 'GJ', sn: 'Gujrat' },
  { sc: 'HP', sn: 'Himachal Pradesh' },
  { sc: 'HR', sn: 'Haryana' },
  { sc: 'JH', sn: 'Jharkhand' },
  { sc: 'JK', sn: 'Jammu and Kashmir' },
  { sc: 'KA', sn: 'Karnataka' },
  { sc: 'KL', sn: 'Kerala' },
  { sc: 'LA', sn: 'Ladakh' },
  { sc: 'MH', sn: 'Maharashtra' },
  { sc: 'ML', sn: 'Meghalaya' },
  { sc: 'MN', sn: 'Manipur' },
  { sc: 'MP', sn: 'Madhya Pradesh' },
  { sc: 'MZ', sn: 'Mizoram' },
  { sc: 'NL', sn: 'Nagaland' },
  { sc: 'OR', sn: 'Odisha' },
  { sc: 'PB', sn: 'Punjab' },
  { sc: 'PY', sn: 'Puducherry' },
  { sc: 'RJ', sn: 'Rajasthan' },
  { sc: 'SK', sn: 'Sikkim' },
  { sc: 'TG', sn: 'Telangana' },
  { sc: 'TN', sn: 'Tamil Nadu' },
  { sc: 'TR', sn: 'Tripura' },
  { sc: 'UP', sn: 'Uttar Pradesh' },
  { sc: 'UT', sn: 'Uttarakhand' },
  { sc: 'WB', sn: 'West Bengal' },
];
